language: python
python:
  - "2.6"
  - "2.7"
before_install: 
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "sudo apt-get install python-dev libevent-dev"
install: 
    - python setup.py develop
    - pip install . -r requirements-tests.pip --use-mirrors
script: ./ci_build.sh
